version: '3'

services:
  lphh_backend:
    image: lphh_backend
    build: 
      context: ./lphh-backend/lphh-api/lphh-api
    container_name: lphh-backend
    ports:
      - "5274:5274"
    depends_on:
      - db
    command: ["dotnet", "ef" , "database update"]
    networks:
      - my-network

  lphh-frontend:
    container_name: lphh-frontend
    image: lphh_frontend
    build: 
      context: ./lphh-frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - lphh_backend
    environment:      
      BACKEND_URL: 'http://lphh_backend:5274'

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: db
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Incorrect!
      - ENCRYPT=false
      - MSSQL_DB=LPHHospital
      - DATABASE=LPHHospital
    networks:
      - my-network
    
  
networks:
  my-network:

    